### ISSUE TITLE
Implement EXSLT functions, e.g. exsl:node-set ?

### ISSUE THREAD

**Issue by Boddlnagg** [shepmaster/sxd-xpath#109] opened 2017-03-29 20:54 UTC
I have an XSLT script that uses the [`node-set`](http://exslt.org/exsl/functions/node-set/exsl.node-set.html) function defined by EXSLT. It works in Firefox, which has some [EXSLT support](https://developer.mozilla.org/en-US/docs/Web/EXSLT). Depending on how hard this would be to implement (`node-set` shouldn't be too hard), I think having it in this Rust library would be great!

**Comment by Boddlnagg** [comment] 2017-03-29 20:54
Oh, I see there already is #50 ... sorry.

**Comment by shepmaster** [comment] 2017-03-31 13:51
Thank you! I'm going to go ahead and close this as a duplicate of #50. I definitely agree that there's a bunch of EXSLT functionality that is super useful.

> (`node-set` shouldn't be too hard)

Implementing functions isn't that bad! You can take a look at the file that [defines all the current functions](https://github.com/shepmaster/sxd-xpath/blob/master/src/function.rs). The [documentation for `Context`](https://docs.rs/sxd-xpath/0.4.0/sxd_xpath/context/struct.Context.html) even shows how you can create user-specified functions.

I'd certainly appreciate a pull request adding `node-set`!

**Closed by shepmaster** 2017-03-31 13:51 UTC

**Comment by Boddlnagg** [comment] 2017-03-31 14:54
I see that implementing `node-set` doesn't make sense right now, because there is no implementation of XSLT yet. The whole point of `node-set` is to turn "Result Tree Fragments" into proper XPath Nodesets, but right now "Result Tree Fragments" do not exist, because they are an addition of XSLT 1.0 to XPath (see https://www.w3.org/TR/xslt#section-Result-Tree-Fragments). I actually remember now that I opened #61 about this almost two years ago 😅 .

Another complication is that EXSLT functions are namespaced (e.g. [` xmlns:exsl="http://exslt.org/common"`](http://exslt.org/exsl/index.html), then you can use `exsl:node-set(...)`), which currently does not seem to be supported and actually also only makes sense in the context of XSLT.

**Comment by shepmaster** [comment] 2017-03-31 18:55
> which currently does not seem to be supported

It should be:

```rust
context.set_function(("http://exslt.org/common", "node-set"), NodeSetFunction)
``` 

> only makes sense in the context of XSLT

Nah, that's a concept of XPath.
